fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: standard
            removePlugins: exportpdf

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
