security:
    # Use the best password hashing algorithm based on the current PHP version
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Load users from the database via the User entity using the email field
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Disable security for the Symfony profiler and static assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main application firewall
        main:
            lazy: true
            provider: app_user_provider

            # Use custom login form authenticator
            custom_authenticator: App\Security\LoginFormAuthenticator
            entry_point: App\Security\LoginFormAuthenticator

            # Enable logout functionality
            logout:
                path: logout
                # target: homepage  # Optional: uncomment to redirect after logout

            # Optional: Remember-me functionality
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

    # Role hierarchy: Admin inherits Client privileges
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CLIENT]
        ROLE_CLIENT: []

    # Access rules for different parts of the application
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }        # Only admins can access /admin
        - { path: ^/apprenant, roles: ROLE_CLIENT }   # Clients and admins can access /dashboard

    access_denied_url: /non-autorise


# Test environment: use lightweight password hashing to speed up tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4           # Minimal bcrypt cost
                time_cost: 3      # Minimal argon time cost
                memory_cost: 10   # Minimal argon memory cost
