security:
    password_hashers:
        # Use the best hashing algorithm available for the current PHP version
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Load users from the database via the User entity and match by email
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Disable security on Symfony profiler and static assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Enable form-based login
            form_login:
                login_path: login          # Route to display the login form (GET)
                check_path: login          # Route to handle form submission (POST)
                username_parameter: email
                password_parameter: password
                default_target_path: homepage  # Redirect after successful login

            # Enable logout functionality
            logout:
                path: app_logout           # Logout route
                target: homepage           # Redirect after logout

    # Role hierarchy: admin inherits client privileges
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CLIENT]
        ROLE_CLIENT: []

    # Access rules for different parts of the site
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }        # Only admins can access /admin
        - { path: ^/dashboard, roles: ROLE_CLIENT }   # Clients and admins can access /dashboard

# Test environment: use light password hashing to speed up test execution
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4           # Lowest possible for bcrypt
                time_cost: 3      # Lowest possible for argon
                memory_cost: 10   # Lowest possible for argon
